/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChinaMap: typeof import('./src/components/ChinaMap.vue')['default']
    CommonHeader: typeof import('./src/components/CommonHeader.vue')['default']
    CommonNotify: typeof import('./src/components/CommonNotify.vue')['default']
    CommonTabs: typeof import('./src/components/CommonTabs.vue')['default']
    CommonTitle: typeof import('./src/components/CommonTitle.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    JiangxiMap: typeof import('./src/components/JiangxiMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
